"""A saved API plan must reproduce through the untouched official generator."""

import hashlib
import json
from pathlib import Path
import secrets
import stat
import subprocess
import sys
from uuid import uuid4

import pytest

from beesmart.config import Settings
from scripts import build_submission as exporter


ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture
def saved_run(tmp_path, synthetic_frames):
    storage = tmp_path / "private"
    dataset_id = uuid4().hex
    dataset = storage / "datasets" / dataset_id
    (dataset / "data").mkdir(parents=True)
    for role, filename in (("profile", "customer_profile.csv"), ("history", "data/change_tariff.csv"),
                           ("tariffs", "data/dict_tariff.csv")):
        synthetic_frames[role].to_csv(dataset / filename, index=False)
    policy = {"schema_version": 1, "source": "openai", "alternative_targets_by_cell": {},
              "priority_arms": [["tariff_a", segment, "tariff_c"] for segment in ("LOW", "MID", "HIGH")]}
    policy_path = storage / "llm" / "policies" / ("a" * 64 + ".json")
    policy_path.parent.mkdir(parents=True)
    policy_path.write_text(json.dumps(policy))
    # No HTTP: manually frozen priorities exercise the same real worker path.
    completed = subprocess.run([sys.executable, "-m", "beesmart.application.worker", "42", "--data-dir", str(dataset),
                                "--policy-path", str(policy_path)], cwd=ROOT,
                               env=exporter._worker_environment(), check=True, capture_output=True, text=True, timeout=30)
    result = next(value["data"] for line in completed.stdout.splitlines()
                  if (value := json.loads(line))["type"] == "result")
    identifier = str(uuid4())
    report = {"id": identifier, "status": "completed", "seed": 42,
              "dataset": {"source": "uploaded", "id": dataset_id}, **result}
    report_path = storage / "runs" / f"{identifier}.json"
    report_path.parent.mkdir()
    report_path.write_text(json.dumps(report))
    return Settings(root=ROOT, storage_dir=storage), report, report_path, policy_path, dataset


def test_export_replays_private_policy_official_generator_and_never_inherits_secrets(saved_run, monkeypatch):
    settings, report, _, policy_path, _ = saved_run
    sentinel = secrets.token_urlsafe(32)
    monkeypatch.setenv("OPENAI_API_KEY", sentinel)
    monkeypatch.setenv("BREV_API_TOKEN", sentinel)
    monkeypatch.setenv("BEESMART_API_TOKEN", sentinel)
    monkeypatch.setenv("PYTHONPATH", "/untrusted-hook")
    real_run = subprocess.run
    environments = []

    def observed_run(*args, **kwargs):
        environments.append(kwargs["env"])
        return real_run(*args, **kwargs)

    monkeypatch.setattr(exporter.subprocess, "run", observed_run)
    output = exporter.build_submission(settings, report["id"])
    assert output == settings.storage_path / "submissions" / report["id"]
    assert (output / "policies/frozen_policy.json").read_bytes() == policy_path.read_bytes()
    assert hashlib.sha256((output / "policies/frozen_policy.json").read_bytes()).hexdigest() == report["diagnostics"]["policy_hash"]
    manifest = json.loads((output / "manifest.json").read_text())
    assert manifest["verified"] is True
    for name in ("environment.py", "mock_environment.py", "scoring_core.py", "local_eval.py", "make_submission.py"):
        original = (ROOT / "organizer" / name).read_bytes()
        assert (output / name).read_bytes() == original
        assert manifest["source_sha256"][name] == hashlib.sha256(original).hexdigest()
    expected = set(exporter.CODE_FILES) | set(exporter.DATA_FILES) | {
        "policies/frozen_policy.json", "requirements.txt", "submission.csv", "manifest.json", "README.txt"}
    assert {str(path.relative_to(output)) for path in output.rglob("*") if path.is_file()} == expected
    assert stat.S_IMODE(output.stat().st_mode) == 0o700
    for path in output.rglob("*"):
        assert stat.S_IMODE(path.stat().st_mode) == (0o700 if path.is_dir() else 0o600)
        if path.is_file():
            assert sentinel.encode() not in path.read_bytes()
    assert len(environments) == 1
    assert all(key not in environments[0] for key in (
        "OPENAI_API_KEY", "BREV_API_TOKEN", "BEESMART_API_TOKEN", "PYTHONPATH"))


@pytest.mark.parametrize("change", ["seed", "status", "policy", "campaign"])
def test_export_fails_closed_and_cleans_partial_artifacts(saved_run, change):
    settings, report, report_path, policy_path, _ = saved_run
    if change == "seed":
        report["seed"] = 43
    elif change == "status":
        report["status"] = "failed"
    elif change == "policy":
        policy_path.unlink()
    else:
        report["campaigns"][0]["campaign_name"] = "This was not generated by this code"
    report_path.write_text(json.dumps(report))
    output = settings.storage_path / "submissions" / "rejected"
    with pytest.raises(exporter.SubmissionExportError):
        exporter.build_submission(settings, report["id"], output=output)
    assert not output.exists()
    assert not list(output.parent.glob(".submission-*"))


def test_export_rejects_repository_source_destination_and_existing_directory(saved_run, tmp_path):
    settings, report, _, _, _ = saved_run
    with pytest.raises(exporter.SubmissionExportError, match="work/"):
        exporter.build_submission(settings, report["id"], output=ROOT / "never-write-export")
    existing = tmp_path / "existing"
    existing.mkdir()
    marker = existing / "keep.txt"
    marker.write_text("keep")
    with pytest.raises(exporter.SubmissionExportError, match="существует"):
        exporter.build_submission(settings, report["id"], output=existing)
    assert marker.read_text() == "keep"


def test_missing_uploaded_dataset_can_be_restored_through_explicit_data_directory(saved_run, tmp_path):
    settings, report, _, _, dataset = saved_run
    restored = tmp_path / "restored-inputs"
    dataset.rename(restored)
    output = exporter.build_submission(settings, report["id"], data_dir=restored)
    assert (output / "submission.csv").is_file()


def test_generator_timeout_removes_private_temporary_directory(saved_run, monkeypatch):
    settings, report, _, _, _ = saved_run

    def timeout(*args, **kwargs):
        raise subprocess.TimeoutExpired(args[0], kwargs["timeout"])

    monkeypatch.setattr(exporter.subprocess, "run", timeout)
    with pytest.raises(exporter.SubmissionExportError, match="лимит времени"):
        exporter.build_submission(settings, report["id"])
    folder = settings.storage_path / "submissions"
    assert list(folder.iterdir()) == []
